{% set name = "ussa1976" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ussa1976-{{ version }}.tar.gz
  sha256: 28eec80a65db5ab84ec79ea1732352bbb137408260f940374fa313c7440faa37

build:
  entry_points:
    - ussa1976 = ussa1976.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - poetry
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - click >=7.0
    - netcdf4 >=1.5.7
    - numpy >=1.22
    - python >={{ python_min }},<4.0
    - scipy >=1.6.3
    - xarray >=0.18.2

test:
  imports:
    - ussa1976
  commands:
    - pip check
    - ussa1976 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nollety/ussa1976
  summary: The U.S. Standard Atmosphere 1976 model.
  description: |
    This package implements the atmosphere thermophysical model provided by the
    National Aeronautics and Space Administration technical report
    NASA-TM-X-74335 published in 1976 and entitled "U.S. Standard Atmosphere,
    1976".
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://ussa1976.readthedocs.io/
  dev_url: https://github.com/nollety/ussa1976

extra:
  recipe-maintainers:
    - nollety
